// Generated by dts-bundle v0.7.3

declare module 'typescript-codecoverage-example' {
    export * from "typescript-codecoverage-example/person";
}

declare module 'typescript-codecoverage-example/person' {
    export default class Person {
        firstName: string;
        lastName: string;
        getFullName(): string;
        getLastName(): string;
    }
}

